# Generated by Django 2.0.5 on 2018-05-06 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privatecode', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('mobile_phone', models.CharField(max_length=40)),
                ('date_of_birth', models.DateField(max_length=8)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=8)),
                ('tshirt_size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('3Xl', '3Xl')], max_length=4)),
                ('address', models.CharField(max_length=255)),
                ('street_address', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('education_level', models.CharField(choices=[('University: First Year', 'University: First Year'), ('University: Second Year', 'University: Second Year'), ('University: Third Year', 'University: Third Year'), ('University: Fourth Year', 'University: Fourth Year'), ('Completed a Two-Year Diploma', 'Completed a Two-Year Diploma'), ('Completed a Bechelors Degree', 'Completed a Bechelors Degree'), ('Post Graduate Studies(Master & PHD)', 'Post Graduate Studies(Master & PHD)')], max_length=255)),
                ('name_of_university_highschool', models.CharField(max_length=255)),
                ('major', models.CharField(max_length=255)),
                ('work_experience', models.TextField(null=True)),
                ('website_link', models.CharField(blank=True, max_length=255, null=True)),
                ('hear_by', models.CharField(choices=[('Presentation we did', 'Presentation we did'), ('Friend', 'Friend'), ('Your Computer Science professor', 'Your Computer Science professor'), ('From a Blog', 'From a Blog'), ('Instagram', 'Instagram'), ('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('Snapchat', 'Snapchat'), ('Sirdablab (Member)', 'Sirdablab (Member)'), ('From a former or current Coded student', 'From a former or current Coded student'), ('LinkedIn', 'LinkedIn'), ('Google', 'Google'), ('Other ', 'Other ')], max_length=255)),
                ('goal', models.TextField()),
                ('background', models.TextField()),
                ('portfolio', models.FileField(null=True, upload_to='')),
                ('cv', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='BootCamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('startdate', models.DateTimeField()),
                ('admissionenddate', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='applicant',
            name='bootcamp',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admission.BootCamp'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
