# Generated by Django 2.0.5 on 2018-05-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_auto_20180508_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='address',
        ),
        migrations.AddField(
            model_name='applicant',
            name='city',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicant',
            name='address_line_2',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicant',
            name='country',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='privatecode',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='street_address',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
