# Generated by Django 2.0.5 on 2018-05-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0003_auto_20180510_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='education_level',
            field=models.CharField(choices=[('High School', 'High School'), ('University: First Year', 'University: First Year'), ('University: Second Year', 'University: Second Year'), ('University: Third Year', 'University: Third Year'), ('University: Fourth Year', 'University: Fourth Year'), ('Completed a Two-Year Diploma', 'Completed a Two-Year Diploma'), ('Completed a Bachelors Degree', 'Completed a Bachelors Degree'), ('Post Graduate Studies(Master & PHD)', 'Post Graduate Studies(Master & PHD)')], max_length=255),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='work_experience',
            field=models.TextField(blank=True, null=True),
        ),
    ]
